// Code generated by protoc-gen-go.
// source: cbs.proto
// DO NOT EDIT!

package cbs_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Header struct {
	NumRows              *uint64 `protobuf:"varint,1,opt,name=num_rows" json:"num_rows,omitempty"`
	BlockSize            *uint64 `protobuf:"varint,2,opt,name=block_size" json:"block_size,omitempty"`
	CompressedBlockSize  *uint64 `protobuf:"varint,3,opt,name=compressed_block_size" json:"compressed_block_size,omitempty"`
	BitmapSize           *uint64 `protobuf:"varint,4,opt,name=bitmap_size" json:"bitmap_size,omitempty"`
	CompressedBitmapSize *uint64 `protobuf:"varint,5,opt,name=compressed_bitmap_size" json:"compressed_bitmap_size,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (this *Header) Reset()         { *this = Header{} }
func (this *Header) String() string { return proto.CompactTextString(this) }
func (*Header) ProtoMessage()       {}

func (this *Header) GetNumRows() uint64 {
	if this != nil && this.NumRows != nil {
		return *this.NumRows
	}
	return 0
}

func (this *Header) GetBlockSize() uint64 {
	if this != nil && this.BlockSize != nil {
		return *this.BlockSize
	}
	return 0
}

func (this *Header) GetCompressedBlockSize() uint64 {
	if this != nil && this.CompressedBlockSize != nil {
		return *this.CompressedBlockSize
	}
	return 0
}

func (this *Header) GetBitmapSize() uint64 {
	if this != nil && this.BitmapSize != nil {
		return *this.BitmapSize
	}
	return 0
}

func (this *Header) GetCompressedBitmapSize() uint64 {
	if this != nil && this.CompressedBitmapSize != nil {
		return *this.CompressedBitmapSize
	}
	return 0
}

func init() {
}
